### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Cabel-T** [joaojacome/bitwarden-ssh-agent#5]
when I exec this script，output error：
python3 bw_add_sshkeys.py
```
INFO:root:Getting Bitwarden session
Traceback (most recent call last):
  File "bw_add_sshkeys.py", line 313, in <module>
    main()
  File "bw_add_sshkeys.py", line 295, in main
    session = get_session()
  File "bw_add_sshkeys.py", line 86, in get_session
    '--quiet'
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bw': 'bw'
```

**Comment by joaojacome** [comment]
You'd need to install the bitwarden CLI to use this tool. Check it out here https://github.com/bitwarden/cli
Good luck!

**Comment by mortee** [comment]
For some reason, I get this error in Termux despite having the BW CLI installed and on my path. It used to work until some time ago.

```
$ git -C ~/bitwarden-ssh-agent/ status -u
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
$ type bw
bw is /data/data/com.termux/files/usr/bin/bw
$ type bw_add_sshkeys.py
bw_add_sshkeys.py is /data/data/com.termux/files/home/bin/bw_add_sshkeys.py
$ ls -l ~/bin/bw_add_sshkeys.py          
lrwxrwxrwx 1 u0_a355 u0_a355 50 Dec  8  2022 /data/data/com.termux/files/home/bin/bw_add_sshkeys.py -> ../bitwarden-ssh-agent/bw_add_sshkeys.py
$ bw_add_sshkeys.py
INFO     Getting Bitwarden session
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/bin/bw_add_sshkeys.py", line 317, in <module>
    main()
  File "/data/data/com.termux/files/home/bin/bw_add_sshkeys.py", line 294, in main
    session = get_session(args.session)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/bin/bw_add_sshkeys.py", line 26, in get_session
    proc_logged = subprocess.run(["bw", "login", "--check", "--quiet"], check=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1899, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bw'
```
